### ISSUE TITLE
Specs not discovered on purescript 0.13

### ISSUE THREAD

**Issue by drewolson** [purescript-spec/purescript-spec-discovery#12]
I’m unable to get spec discovery working on purescript 0.13 and the newest package set. I’ve created a repo that demonstrates the problem — https://github.com/drewolson/discovery-example 

I’ve also noticed that the documentation seems out of date regarding spec’s switch to `Aff` in that package set, though it appears to include an RC version of spec, so perhaps these changes are coming in the future. Thanks!

**Comment by drewolson** [comment]
I was able to narrow the issue down to this line https://github.com/purescript-spec/purescript-spec-discovery/blob/master/src/Test/Spec/Discovery.js#L16

In the newest version of spec, the `spec` export is an `object`, not a `function`.

**Comment by owickstrom** [comment]
@drewolson Thanks for the report! Maybe it suffices to check that `module.spec !== undefined`, then, and have it compatible with <0.13 and 0.13. Would you like to submit a PR?

**Comment by drewolson** [comment]
@owickstrom I went ahead and created a PR.
