### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-spec/purescript-spec-discovery#18]
Master has some changes that the latest version of `specs` seems to need.

**Comment by i-am-the-slime** [comment]
I would need this for i-am-the-slime/purescript-react-testing-library#4 . I'm also willing to help out with this as a maintainer if you need help @owickstrom

**Comment by owickstrom** [comment]
@i-am-the-slime I've invited you to the maintainers team, would love some help!

Ping me if I should do a version bump and release any way.
