### ISSUE TITLE
New version for purescript-spec ^1.0.0

### ISSUE THREAD

**Issue by tonyd256** [purescript-spec/purescript-spec-discovery#4]
Thanks for the awesome lib! Would you be able to push a new release for what's currently on master? The latest release references an old spec version. It's updated on master but there is no corresponding release. It all works fine anyways but would be nice to not have the dependency conflict while installing.

**Comment by owickstrom** [comment]
Thanks! Oh, sure, I must have forgot earlier. Here's a 1.0.0 release: https://pursuit.purescript.org/packages/purescript-spec-discovery/1.0.0
