### ISSUE TITLE
Support running PSCI in a browser

### ISSUE THREAD

**Issue by vyorkin** [purescript-spec/purescript-spec-discovery#6]
Hello, first of all, I want to say thank you for the cool package! 👍 

I've just noticed one small issue.
It looks like it doesn't play well together with `pulp psci --port 8080`, which is [useful](https://github.com/paf31/24-days-of-purescript-2016/blob/master/8.markdown#8-psci-in-the-browser) (evals compiled js in a browser).

![error1](https://user-images.githubusercontent.com/988849/38277208-44ce1cb4-37a0-11e8-82c8-d919ad9469fa.png)

[Here is the repo](https://github.com/vyorkin-forks/purescript-graphics-vis/blob/issue-repro/bower.json#L25) which reproduces the issue mentioned above.
I've also left some instructions in [README](https://github.com/vyorkin-forks/purescript-graphics-vis/tree/issue-repro#how-to-reproduce-the-issue).

**Comment by owickstrom** [comment]
Thanks! Yes, this package only supports NodeJS environments right now. I had some ideas about using Webpack and its API (can't remember the name) to do some kind of reflection on the bundled modules, but I'm not working on this anymore and have no time for it. Also, I don't know if that Webpack approach would work with `pulp psci` server command.

If you'd be interested in trying to extend support to browser environments, I'd accept a PR.

**Comment by vyorkin** [comment]
Smth like this could work: https://github.com/garyb/purescript-debug/blob/master/src/Debug/Trace.js#L4 (the basic idea)
You're already checking if `require` is `undefined`,
so maybe instead of throwing an error we can just return an empty array of specs in that case?

UPD:
Ok, I see, it actually breaks earlier, at `import Node.FS` [here](https://github.com/owickstrom/purescript-spec-discovery/blob/master/src/Test/Spec/Discovery.purs#L6), because https://github.com/purescript-node/purescript-node-fs/blob/6a1651cb16ad77c2e9d7f64f7ea10d3ec129b14c/src/Node/FS/Stats.js#L3. 
I have no idea how to fix this for now :)

**Comment by fsoikin** [comment]
Closing this due to 5 years of inactivity.
