### ISSUE TITLE
Please tag and publish new version

### ISSUE THREAD

**Issue by paluh** [purescript-spec/purescript-spec-discovery#8]
It seems that updates for PureScript 0.12 has not been published...

**Comment by kazk** [comment]
@owickstrom can you please release the new version?
I'd like to use this package with `psc-package`. I didn't realize `v2.0.0` wasn't the latest until `psc-package verify spec-discovery` failed :(

**Comment by owickstrom** [comment]
3.0.0 now tagged and published: https://pursuit.purescript.org/packages/purescript-spec-discovery/3.0.0

Sorry for the wait!
